name: CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy:
    #needs: []
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            whoami
            ls -al
            docker run hello-world
