name: CD

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    # needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.HOST}} # Remote server address / ip - required
          user: ${{secrets.USER}} # Remote server user - required
          private_key: ${{secrets.PRIVATE_KEY}} # Private ssh key registered on the remote server - required
          command: echo 'hello world' # Command to be executed - Default: echo 'hello world' - optional
